.eslintrc.json
index.js
instructions.json
lib/use-lane.js
lib/utils.js
package.json
test/index.js

This adds handling for all types. This also adds a switch statement for handling special types at runtime that must always be modified and that cannot be expressed in the `instructions.json` file.
/cc @freenerd

Add all types

---

CHANGELOG.md
instructions.json
test/fixtures/v5/rotary/name_destination.json
test/fixtures/v5/rotary/name_name.json
test/index_test.js

Looks like I missed this in #27

Fix rotary name 'exit onto'

---

CHANGELOG.md
instructions.json
test/fixtures/v5/continue/uturn.json
test/fixtures/v5/continue/uturn_no_name.json
test/fixtures/v5/merge/uturn.json
test/fixtures/v5/merge/uturn_no_name.json
test/fixtures/v5/notification/uturn.json
test/fixtures/v5/notification/uturn_no_name.json
test/fixtures/v5/roundabout_turn/uturn.json
test/fixtures/v5/roundabout_turn/uturn_destinations.json
test/fixtures/v5/roundabout_turn/uturn_no_name.json
test/fixtures/v5/turn/uturn.json
test/fixtures/v5/turn/uturn_no_name.json

Fix #33 
Use `Make a U-turn` everywhere

Better U-Turn instructions

---

index.js
test/fixtures/v5/other/way_name_ref_mapbox_hack_3.json

Backwards compatibility is hard 😢

Fix duplicate name/ref issue

---

CHANGELOG.md
LICENSE.txt

Put under Simplified BSD License

---

CHANGELOG.md
instructions/en.json
test/fixtures/v5/rotary/exit_10.json
test/fixtures/v5/rotary/exit_1_default.json
test/fixtures/v5/rotary/exit_1_destination.json
test/fixtures/v5/rotary/exit_1_name.json
test/fixtures/v5/rotary/exit_2.json
test/fixtures/v5/rotary/exit_3.json
test/fixtures/v5/rotary/exit_4.json
test/fixtures/v5/rotary/exit_5.json
test/fixtures/v5/rotary/exit_6.json
test/fixtures/v5/rotary/exit_7.json
test/fixtures/v5/rotary/exit_8.json
test/fixtures/v5/rotary/exit_9.json
test/fixtures/v5/rotary/name_exit_default.json
test/fixtures/v5/rotary/name_exit_destination.json
test/fixtures/v5/rotary/name_exit_name.json
test/fixtures/v5/roundabout/exit_default.json
test/fixtures/v5/roundabout/exit_destination.json
test/fixtures/v5/roundabout/exit_name.json

Use numeric ordinals

---

instructions/zh.json

Added Chinese instructions (zh.json)

add Chinese instructions

---

instructions.js
instructions/nl.json
test/instructions_test.js

Re-roll of https://github.com/Project-OSRM/osrm-text-instructions/pull/64 by @milovanderlinden with fixed merge conflict

Added Dutch translation

---

CHANGELOG.md
instructions/zh-Hans.json

Zh copy edits

---

.eslintrc.json
package.json
test/fixtures_test.js
test/index_test.js
test/instructions_test.js

Enable eslint on tests

---

CHANGELOG.md
instructions/en.json
test/fixtures/v5/continue/straight_destination.json
test/fixtures/v5/continue/straight_name.json

Let's make this more concise, when it's straight it's clear where to go.

Briefer continue instructions

---

CHANGELOG.md
package.json

Changelog and bump - v0.4.0

---

languages.js
languages/translations/pl.json

Polish translation

---

CHANGELOG.md
package.json

Release v0.5.2

---

languages/translations/it.json
test/fixtures/v5/merge/sharp_left_exit.json
test/fixtures/v5/merge/sharp_left_name.json
test/fixtures/v5/merge/slight_left_exit.json
test/fixtures/v5/merge/slight_left_name.json

Small fixes to italian translation.
(From transifex)

Updated italian translation

---

index.js

Fixed a test failure caused by merging #148 and #149, which had a latent conflict.
/cc @bsudekum

Fix error tokenizing ref

---

Readme.md

Followup to #170.
/cc @mcwhittemore

Fix table in readme

---

CHANGELOG.md
languages/translations/de.json
languages/translations/en.json
languages/translations/eo.json
languages/translations/es-ES.json
languages/translations/es.json
languages/translations/fr.json
languages/translations/id.json
languages/translations/it.json
languages/translations/nl.json
languages/translations/pl.json
languages/translations/pt-BR.json
languages/translations/ro.json
languages/translations/ru.json
languages/translations/sv.json
languages/translations/tr.json
languages/translations/uk.json
languages/translations/vi.json
languages/translations/zh-Hans.json
package.json
test/languages_test.js

Adds an instruction worded for upcoming arrival

---

Readme.md

add info about adding new instruction options

---

CHANGELOG.md
languages/translations/de.json

Update German translation

---

CHANGELOG.md
languages/translations/zh-Hans.json
test/fixtures/v5/arrive_waypoint_name/left.json
test/fixtures/v5/arrive_waypoint_name/no_modifier.json
test/fixtures/v5/arrive_waypoint_name/right.json
test/fixtures/v5/arrive_waypoint_name/sharp_left.json
test/fixtures/v5/arrive_waypoint_name/sharp_right.json
test/fixtures/v5/arrive_waypoint_name/slight_left.json
test/fixtures/v5/arrive_waypoint_name/slight_right.json
test/fixtures/v5/arrive_waypoint_name/straight.json
test/fixtures/v5/arrive_waypoint_name/uturn.json

Updated Simplified Chinese translations from Transifex, courtesy of @chriswu42.
/cc @danpaz @frederoni

Update Simplified Chinese translations

---

languages/translations/fr.json
test/fixtures/v5/merge/left_default.json
test/fixtures/v5/merge/left_destination.json
test/fixtures/v5/merge/left_exit.json
test/fixtures/v5/merge/left_exit_destination.json
test/fixtures/v5/merge/left_name.json
test/fixtures/v5/merge/right_default.json
test/fixtures/v5/merge/right_destination.json
test/fixtures/v5/merge/right_exit.json
test/fixtures/v5/merge/right_exit_destination.json
test/fixtures/v5/merge/right_name.json

Updated a few French translations based on Transifex.
/cc @Penegal @danpaz

Update French translations

---

languages.js

Fixed a typo in an internal variable name.
/cc @danpaz

Fix typo in abbreviations code

---

.github/workflows/ci.yml
.travis.yml

I want to contribute into here a bit, so would be nice to have at least simple CI :)

Add simple CI
