Project-OSRM/osrm-text-instructions

index.js
test/fixtures/v5/unkown_left.json

> new identifiers might be introduced without API change Types unknown to the client should be handled like the turn type, the existance of correct modifier values is guranteed.
https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#properties-4
/cc @bsudekum

Handle unknown turn types

---

CHANGELOG.md
instructions.json
test/fixtures/v5/end_of_road/left.json
test/fixtures/v5/end_of_road/left_no_name.json
test/fixtures/v5/end_of_road/right.json
test/fixtures/v5/end_of_road/right_destinations.json
test/fixtures/v5/end_of_road/right_no_name.json
test/fixtures/v5/end_of_road/sharp_left.json
test/fixtures/v5/end_of_road/sharp_left_no_name.json
test/fixtures/v5/end_of_road/sharp_right.json
test/fixtures/v5/end_of_road/sharp_right_no_name.json
test/fixtures/v5/end_of_road/slight_left.json
test/fixtures/v5/end_of_road/slight_left_no_name.json
test/fixtures/v5/end_of_road/slight_right.json
test/fixtures/v5/end_of_road/slight_right_no_name.json

Let's only mention end of the road when it makes semantic a lot of change, otherwise keep it short.
We might want to revise this decision, e.g. by moving end of the road to the front of the instruction. For now I'm keeping parity with the state we had before in Mapbox Directions.

Only mention end-of-the-road on uturn

---

index.js

Let's output invalid types, so they can be detected from logs later.

Console log invalid types

---

CHANGELOG.md
instructions.json
test/fixtures/v5/use_lane/all_lanes.json
test/fixtures/v5/use_lane/left.json
test/fixtures/v5/use_lane/left_lane.json
test/fixtures/v5/use_lane/left_lane_no_name.json
test/fixtures/v5/use_lane/oox.json
test/fixtures/v5/use_lane/oox_destinations.json
test/fixtures/v5/use_lane/right.json
test/fixtures/v5/use_lane/sharp_left.json
test/fixtures/v5/use_lane/sharp_right.json
test/fixtures/v5/use_lane/slight_left.json
test/fixtures/v5/use_lane/slight_right.json
test/fixtures/v5/use_lane/straight.json
test/fixtures/v5/use_lane/uturn.json
test/fixtures/v5/use_lane/xo.json
test/fixtures/v5/use_lane/xoo.json
test/fixtures/v5/use_lane/xxo.json
test/fixtures/v5/use_lane/xxoo.json
test/fixtures/v5/use_lane/xxoxo.json

I'm a bit unclear how `type: use lane` will actually be used.
It feels to me that `name` and `destination` only make sense, if they actually distinguish the lanes from each other. Since all lanes are on the same OSM way though, all lanes would have the same `name/destination` information. Thus we should not include that information in the text instruction, since it will be the same for all lanes.
We could re-introduce `destination` instructions if OSRM would support the [`destination:lanes` OSM tag](https://wiki.openstreetmap.org/wiki/Lanes), ticketed here https://github.com/Project-OSRM/osrm-backend/issues/2553#issuecomment-227067935 already
/cc @MoKob @daniel-j-h @bsudekum

No way_name/destination with use lane

---

CHANGELOG.md
index.js

This allows clients to customize instructions.json in-code. I've successfully used this in a project to add html tags like this:
```js
traverse(osrmTextInstructions.instructions).forEach(function (node) {
if (node.constructor === String) {
this.update(node.
replace('{way_name}', '<span class="way-name">{way_name}</span>').
replace('{destination}', '<span class="destination">{destination}</span>'),
true
);
}
});
```

Allow runtime customizations of instructions.json

---

CHANGELOG.md
index.js
instructions/de.json

This was inconsistent and only worked in the `de` version so far, now all translations use the same key.

Standardize on capitalizeFirstLetter meta key

---

CHANGELOG.md
Readme.md
index.js
test/index_test.js

Fixes #52 
This removes the previous hack of monkey-patching the instructions object

Add options.hooks.tokenizedInstruction

---

Readme.md

Expanded the description in the readme to link to OSRM and the Swift and Java ports. Also removed the WIP notice and performed a little copyediting.
@freenerd, any reason to leave the WIP notice in place?
/cc @bsudekum @cammace

Expand description in readme

---

languages/translations/ru.json
test/fixtures/v5/end_of_road/left_destination.json
test/fixtures/v5/end_of_road/left_name.json
test/fixtures/v5/end_of_road/right_destination.json
test/fixtures/v5/end_of_road/right_name.json
test/fixtures/v5/end_of_road/sharp_left_destination.json
test/fixtures/v5/end_of_road/sharp_left_name.json
test/fixtures/v5/end_of_road/sharp_right_destination.json
test/fixtures/v5/end_of_road/sharp_right_name.json
test/fixtures/v5/end_of_road/slight_left_destination.json
test/fixtures/v5/end_of_road/slight_left_name.json
test/fixtures/v5/end_of_road/slight_right_destination.json
test/fixtures/v5/end_of_road/slight_right_name.json
test/fixtures/v5/end_of_road/uturn_name.json
test/fixtures/v5/new_name/left_default.json
test/fixtures/v5/new_name/left_destination.json
test/fixtures/v5/new_name/left_name.json
test/fixtures/v5/new_name/right_default.json
test/fixtures/v5/new_name/right_destination.json
test/fixtures/v5/new_name/right_name.json
test/fixtures/v5/new_name/straight_default.json
test/fixtures/v5/new_name/straight_destination.json
test/fixtures/v5/new_name/straight_name.json

Running `npm run transifex` produced these changes in the Russian translation, which means the repository is out of sync with Transifex. @yuryleb, can you review? Thanks!

Update Russian translations from Transifex

---

.npmignore

I suppose that transifex.auth file with Transifex authitication was published into NPM repository by mistake. This commit excludes this file from publishing.

Don't publish transifex.auth into NPM

---

languages/translations/nl.json
test/fixtures/v5/rotary/exit_10.json
test/fixtures/v5/rotary/exit_1_default.json
test/fixtures/v5/rotary/exit_1_destination.json
test/fixtures/v5/rotary/exit_1_name.json
test/fixtures/v5/rotary/exit_2.json
test/fixtures/v5/rotary/exit_3.json
test/fixtures/v5/rotary/exit_4.json
test/fixtures/v5/rotary/exit_5.json
test/fixtures/v5/rotary/exit_6.json
test/fixtures/v5/rotary/exit_7.json
test/fixtures/v5/rotary/exit_8.json
test/fixtures/v5/rotary/exit_9.json
test/fixtures/v5/rotary/name_exit_default.json
test/fixtures/v5/rotary/name_exit_destination.json
test/fixtures/v5/rotary/name_exit_name.json
test/fixtures/v5/roundabout/exit_default.json
test/fixtures/v5/roundabout/exit_destination.json
test/fixtures/v5/roundabout/exit_name.json

Pulled the Dutch localization from Transifex to use numerals instead of spelling out the ordinals.

Update Dutch ordinals from Transifex

---

CHANGELOG.md
Readme.md
index.js
languages.js
package.json
scripts/transifex.js
test/fixtures_test.js
test/index_test.js
test/languages_test.js

This PR introduces support for multiple language support. ~~Right now all language files are always loaded. With this PR, the developer can decide which language files to require. During test instruction compilation, the language used can be chosen. This allows us to scale this project to large numbers of languages, without bloating data downloaded in browsers for all users.~~
The module API as well as internal APIs have breaking changes, since we had to change several function signatures.
TODOs
CC @freenerd 
edit: We will continue to load every language for now because browserify doesn't support dynamic requires. ([cf @freenerd's comment](ttps://github.com/Project-OSRM/osrm-text-instructions/pull/107#issuecomment-302864645))

Multiple language support

---

languages/translations/en.json
test/fixtures/v5/new_name/straight_destination.json
test/fixtures/v5/new_name/straight_exit.json
test/fixtures/v5/new_name/straight_exit_destination.json
test/fixtures/v5/new_name/straight_name.json

This updates `new name` maneuvers to match `continue` maneuvers when the modifier is `straight`.

Remove extra word "straight" for `new name` maneuvers

---

languages/translations/en.json
test/fixtures/v5/off_ramp/right_exit.json
test/fixtures/v5/off_ramp/sharp_right_exit.json
test/fixtures/v5/off_ramp/slight_right_exit.json

Fixes consistency so we're announcing `on the right` for all instructions. The more verbose alternative to https://github.com/Project-OSRM/osrm-text-instructions/pull/124.

Add missing 'on the right' to exit instructions.

---

CHANGELOG.md
index.js
languages/translations/de.json
languages/translations/en.json
languages/translations/es.json
languages/translations/fr.json
languages/translations/id.json
languages/translations/it.json
languages/translations/nl.json
languages/translations/pl.json
languages/translations/pt-BR.json
languages/translations/ru.json
languages/translations/sv.json
languages/translations/uk.json
languages/translations/vi.json
languages/translations/zh-Hans.json
test/index_test.js

There are times when one wants to link two instructions or prefix them with a message. These `phrases` should be translated with the same level of detail as the rest of this project, so I think they should live here. That said, I'm not quite sure how they should be added to the translation files so currently I've only added these to `en.json`.
This PR adds a `phases` to `v5` of the translations along with these new continue phrases.
- continue.default.distance
- continue.default.namedistance
- continue.straight.distance
I think this will close https://github.com/Project-OSRM/osrm-text-instructions/issues/88.

Add phrases for post instruction processing

---

CHANGELOG.md
index.js
test/index_test.js

For consistency with `compile()`, let’s have `language` be the first argument instead of the last. It reads better this way anyhow: since `tokens` is often an inline object literal, it’s easy to forget to specify the language afterwards.
/ref https://github.com/Project-OSRM/osrm-text-instructions/pull/146#issuecomment-328217729
/cc @mcwhittemore

Swap arguments to tokenize

---

CHANGELOG.md
index.js
languages/translations/en.json

Added a format string for a name-ref combination, [for consistency with the iOS navigation SDK](https://github.com/mapbox/mapbox-navigation-ios/blob/447ccaa73d4e1d8a7578e40d86cb5e59df5f2d56/MapboxCoreNavigation/Resources/Base.lproj/Localizable.strings#L14).
This string is primarily meant for display. For example, Chinese uses different characters for the parentheses. However, it may affect speech synthesis in some text-to-speech engines. I’m open to moving the string to a different section of the translations file than `phrase`.
Fixes #131.
/cc @mcwhittemore @bsudekum

Make parentheses around ref localizable

---

index.js

Used ES5 lambda function with Array.some() introduced in #129 is incompatible with ES4-based Uglify/Browserify called by OSRM frontend.
This PR replaces Array.some() call with Array.indexOf().

Replace ES5 lambda in Array.some() with Array.indexOf()

---

languages/translations/en.json
test/fixtures/v5/phrase/two_linked.json
test/fixtures/v5/phrase/two_linked_by_distance.json

Added commas to the linked phrase strings, for a more natural cadence and consistency with the iOS navigation SDK:
https://github.com/mapbox/mapbox-navigation-ios/blob/447ccaa73d4e1d8a7578e40d86cb5e59df5f2d56/MapboxCoreNavigation/Resources/Base.lproj/Localizable.strings#L7-L11
Once #146 lands, the stub translations and test fixtures will need to be updated.
/cc @mcwhittemore @lyzidiamond

Add commas to linked phrases

---

.gitattributes
scripts/transifex.js

Current `ESLint` [settings](https://github.com/Project-OSRM/osrm-text-instructions/blob/master/.eslintrc.json#L76-L79) expect only LF line breaks in JS files; `JSON.stringify()` used by `npm run transifex` and `UPDATE=1 npm test` writes LF line breaks for generated JSON files.
This is the problem for Windows users with default `auto` line breaks option - all files after regeneration became invalid for `ESLint` and changed for `git`.
This PR adds repository option to always checkout JS and JSON files with expected LF line breaks. This is a bit inconvenient to work with them in Windows but makes further life much more easier.

Force LF line breaks for JS & JSON files

---

CHANGELOG.md
index.js
test/index_test.js

New functionality to allow users of this module to have the same `wayName` logic as used in compile.

expose getWayName from compile for other use cases

---

.eslintrc.json
CHANGELOG.md
Readme.md
index.js
languages.js
test/index_test.js
test/languages_test.js

This PR adds support for trying to find locales which we currently do not support. This gist of it is, that if a developer provides `es-MX`, we should give them instructions provides by `es`.
This also moves to use `en` when a language is not found.
/cc @mcwhittemore @1ec5

Add fallback code for unsupported locales

---

.eslintrc.json
CHANGELOG.md
Readme.md
index.js
test/index_test.js

Added a `formatToken` option to `compile`, `getWayName`, and `tokenize` that gives the client an opportunity to manipulate a road name or other token value after any transformations built into this library but before the value is inserted into the overall instruction string. This feature is based on a similar feature built into the Swift version of this library.
Serving suggestion:
```js
var instruction = osrmTextInstructions.compile(language, step, {
formatToken: function (token, value) {
// Mark up numbers to be pronounced like numbers in addresses.
value = value.replace(/\w*[\d.-]+\w*/g, `<say-as interpret-as="address">${value}</say-as>`);
// Wrap road names in their pronunciations, if available.
switch (token) {
case 'name': case 'way_name':
return step.pronunciation ? `<phoneme …
```

Accept callback for formatting tokens

---

CHANGELOG.md
languages/translations/de.json
languages/translations/en.json
languages/translations/eo.json
languages/translations/es-ES.json
languages/translations/es.json
languages/translations/fr.json
languages/translations/id.json
languages/translations/it.json
languages/translations/nl.json
languages/translations/pl.json
languages/translations/pt-BR.json
languages/translations/ro.json
languages/translations/ru.json
languages/translations/sv.json
languages/translations/tr.json
languages/translations/uk.json
languages/translations/vi.json
languages/translations/zh-Hans.json
test/fixtures_test.js
test/languages_test.js

add depart with distance

---

CHANGELOG.md
package.json

- Added a `formatToken` option to `compile`, `getWayName`, and `tokenize` that allows you to manipulate any token value after any grammar or capitalization rules are applied but before the value is inserted into the instruction. [#170](https://github.com/Project-OSRM/osrm-text-instructions/pull/170)
- Removed the `options` parameter to this module, including the `tokenizedInstruction` hook. Use the `formatToken` option instead. [#170](https://github.com/Project-OSRM/osrm-text-instructions/pull/170)
- Added `namedistance` option to the depart instructions and added tests for `namedistance` in depart and continue instructions. Some typo fixes. [#177](https://github.com/Project-OSRM/osrm-text-instructions/pull/177#discussion_r145279715)

0.10.0 release

---

languages/overrides/ru.js
languages/translations/ru.json
test/fixtures/v5/rotary/name_default.json
test/fixtures/v5/rotary/name_destination.json
test/fixtures/v5/rotary/name_exit.json
test/fixtures/v5/rotary/name_exit_default.json
test/fixtures/v5/rotary/name_exit_destination.json
test/fixtures/v5/rotary/name_exit_exit.json
test/fixtures/v5/rotary/name_exit_exit_destination.json
test/fixtures/v5/rotary/name_exit_name.json
test/fixtures/v5/rotary/name_name.json

Just make Russian rotary instructions some shorter.
This is slightly related with issue #173 "Remove traffic circle names from the roundabout and rotary instructions" - IMHO rotary names should not be removed here but actually these instructions really look too long especially in Russian.

Shorten Russian rotary instructions

---

Grammar.md
Readme.md

Some links in Readme.md and Grammar.md to project source files are broken.
This PR fixes them.

Fix broken links in Readme files

---

CHANGELOG.md
index.js
test/index_test.js

When the step’s way has only a ref or a name, call `formatToken` to give the client the opportunity to manipulate that ref or name, just as it would if the way has both a ref and a name.
/cc @mcwhittemore

Call formatToken on bare refs and names

---

CHANGELOG.md
index.js
test/fixtures/v5/other/way_name_destination_refs.json
test/fixtures_test.js

The logic for selecting the first destination was too simplistic, failing to account for the `Ref: Destination` format in the `destination` property.
Fixes #135.
/cc @lyzidiamond

Consistently choose the first destination ref and destination

---

CHANGELOG.md
package.json

need a ✅ to get this out the door! @1ec5 
- Fixed inconsistent destinations when a ramp leads to multiple route……s towards multiple places. [#197](https://github.com/Project-OSRM/osrm-text-instructions/pull/197)
- Removed left/right for off ramps unless it doesn't match driving side. [#199](https://github.com/Project-OSRM/osrm-text-instructions/pull/199)

release 0.11.0

---

Readme.md

We instruct people to push to master, but master is protected and you can't push to it. This update reflects that change in the readme.

fix instructions to reflect that master is protected

---

CHANGELOG.md

#233 added a blurb about Simplified Chinese updates to the wrong section of the changelog (due to releasing after the PR was first pushed). This PR moves the blurb to the “master” section for the upcoming release.
/cc @danpaz

Update changelog for Simplified Chinese updates

---

CHANGELOG.md
languages/overrides/fr.js
languages/translations/fr.json
test/fixtures/v5/arrive_waypoint_name/right.json

Match articles in French instructions with any number of whitespaces between article and `{waypoint_name}` to fix #275 issue.
@1ec5, should I update change log for this 1 char change in French override script?

Improve article matching in French instructions

---

CHANGELOG.md
package.json

- Added a Yoruba localization. [#284](https://github.com/Project-OSRM/osrm-text-instructions/pull/284)
- Renamed “traffic circle” to “roundabout” in the English localization. [#285](https://github.com/Project-OSRM/osrm-text-instructions/pull/285)
- Rewrote the Burmese localization. [#282](https://github.com/Project-OSRM/osrm-text-instructions/pull/282)
- Fixed typographical errors in Italian. [#281](https://github.com/Project-OSRM/osrm-text-instructions/pull/281)
- Fixed grammatical errors in Danish. [#286](https://github.com/Project-OSRM/osrm-text-instructions/pull/286)

Release v0.13.4
